"""add sipp_ssh_root_password column

Revision ID: 60d37f6b264b
Revises: f25628f7b46a
Create Date: 2026-07-29 23:46:55.711132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d37f6b264b'
down_revision: Union[str, Sequence[str], None] = 'f25628f7b46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vcs_settings', sa.Column('sipp_ssh_root_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vcs_settings', 'sipp_ssh_root_password')
    # ### end Alembic commands ###
