"""create test_runs call_events call_flow_diagrams tables

Revision ID: c0fd481e3853
Revises: b1f3a9c7d2e4
Create Date: 2026-07-28 08:09:18.479246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fd481e3853'
down_revision: Union[str, Sequence[str], None] = 'b1f3a9c7d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PARSING', 'DONE', 'FAILED', 'ERROR', name='testrunstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_host', sa.String(length=255), nullable=True),
    sa.Column('raw_log_path', sa.String(length=512), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_test_case_id'), 'test_runs', ['test_case_id'], unique=False)
    op.create_table('call_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('VCTP_LOG', 'VCSM_LOG', 'VCMM_LOG', 'VCMC_LOG', 'SIPP_LOG', name='calleventsource', native_enum=False, length=16), nullable=False),
    sa.Column('raw_line', sa.Text(), nullable=False),
    sa.Column('parsed_type', sa.String(length=64), nullable=False),
    sa.Column('call_id', sa.String(length=255), nullable=True),
    sa.Column('reason_code', sa.Integer(), nullable=True),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_events_call_id'), 'call_events', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_events_run_id'), 'call_events', ['run_id'], unique=False)
    op.create_table('call_flow_diagrams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('mermaid_source', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_flow_diagrams_run_id'), 'call_flow_diagrams', ['run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_flow_diagrams_run_id'), table_name='call_flow_diagrams')
    op.drop_table('call_flow_diagrams')
    op.drop_index(op.f('ix_call_events_run_id'), table_name='call_events')
    op.drop_index(op.f('ix_call_events_call_id'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_test_runs_test_case_id'), table_name='test_runs')
    op.drop_table('test_runs')
    # ### end Alembic commands ###
