"""create vcs_settings table

Revision ID: f25628f7b46a
Revises: c0fd481e3853
Create Date: 2026-07-29 23:17:09.060993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25628f7b46a'
down_revision: Union[str, Sequence[str], None] = 'c0fd481e3853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vcs_settings',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('vcs_ssh_host', sa.String(length=255), nullable=True),
    sa.Column('vcs_ssh_port', sa.Integer(), nullable=True),
    sa.Column('vcs_ssh_username', sa.String(length=255), nullable=True),
    sa.Column('vcs_ssh_password', sa.String(length=255), nullable=True),
    sa.Column('vcs_ssh_private_key_path', sa.String(length=512), nullable=True),
    sa.Column('vcs_ssh_known_hosts', sa.String(length=512), nullable=True),
    sa.Column('sipp_exec_mode', sa.String(length=16), nullable=True),
    sa.Column('sipp_ssh_host', sa.String(length=255), nullable=True),
    sa.Column('sipp_ssh_port', sa.Integer(), nullable=True),
    sa.Column('sipp_ssh_username', sa.String(length=255), nullable=True),
    sa.Column('sipp_ssh_password', sa.String(length=255), nullable=True),
    sa.Column('sipp_ssh_private_key_path', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vcs_settings')
    # ### end Alembic commands ###
